# Generated by Django 5.0.6 on 2025-11-11 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Educator',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nick_name', models.CharField(db_column='nick_name', max_length=255, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('EDUCATOR', 'EDUCATOR'), ('ADMIN', 'ADMIN')], default='EDUCATOR', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('publication_type', models.CharField(choices=[('ARTICLE', 'ARTICLE'), ('FORUM', 'FORUM')], db_column='publication_type', max_length=20)),
                ('content_url', models.CharField(db_column='content_url', max_length=1000)),
                ('educator', models.ForeignKey(db_column='educator_id', on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='core.educator')),
            ],
        ),
        migrations.CreateModel(
            name='Commentary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('content', models.TextField(max_length=2000)),
                ('educator', models.ForeignKey(db_column='educator_id', on_delete=django.db.models.deletion.CASCADE, related_name='commentaries', to='core.educator')),
                ('publication', models.ForeignKey(db_column='publication_id', on_delete=django.db.models.deletion.CASCADE, related_name='commentaries', to='core.publication')),
            ],
        ),
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=512, unique=True)),
                ('expiry_date', models.DateTimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='refresh_token', to='core.user')),
            ],
        ),
        migrations.AddField(
            model_name='educator',
            name='user',
            field=models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='educator', to='core.user'),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribed', models.ForeignKey(db_column='subscribed_id', on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='core.educator')),
                ('subscriber', models.ForeignKey(db_column='subscriber_id', on_delete=django.db.models.deletion.CASCADE, related_name='following', to='core.educator')),
            ],
            options={
                'unique_together': {('subscriber', 'subscribed')},
            },
        ),
    ]
